############################
# 1) Build do BACKEND Java #
############################
FROM maven:3.9.9-amazoncorretto-21-alpine AS backend-build

WORKDIR /getmoneyBackend

COPY getmoneyBackend/pom.xml .
RUN mvn dependency:go-offline -q

COPY getmoneyBackend/src ./src
RUN mvn clean package -DskipTests -q

#########################################
# 2) Build do APK COM ANDROID SDK #
#########################################
FROM eclipse-temurin:21-jdk AS mobile-build

# Instala dependências para Android SDK
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    cmake \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*

# MANTÉM Node.js v22.18.0 (igual ao seu projeto)
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

# Configura Android SDK
ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_SDK_ROOT=$ANDROID_HOME
RUN mkdir -p $ANDROID_HOME
RUN curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip && \
    unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools && \
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest && \
    rm sdk-tools.zip

ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

# Aceita licenças e instala platform + NDK
RUN yes | sdkmanager --licenses
RUN sdkmanager \
    "platform-tools" \
    "platforms;android-34" \
    "build-tools;34.0.0" \
    "ndk;27.1.12297006" \
    "cmake;3.22.1"

WORKDIR /getmoneyFrontend

# Copia APENAS arquivos necessários para cache
COPY getmoneyFrontend/package*.json ./
COPY getmoneyFrontend/app.json ./
COPY getmoneyFrontend/eas.json ./
RUN npm ci --silent --no-optional

# Copia o resto do código
COPY getmoneyFrontend/ ./

# Build do APK
RUN npx expo prebuild --platform android

# Configuração do Gradle - FOCAR NO LOCAL.PROPERTIES
WORKDIR /getmoneyFrontend/android

# CRIA local.properties (SOLUÇÃO PRINCIPAL)
RUN echo "sdk.dir=$ANDROID_HOME" > local.properties && \
    echo "## Generated by Dockerfile" >> local.properties

# Verifica se o arquivo foi criado
RUN cat local.properties

# Configurações MÍNIMAS do Gradle
RUN echo "org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8" > gradle.properties && \
    echo "org.gradle.daemon=false" >> gradle.properties

RUN chmod +x ./gradlew

# Verifica a versão do Gradle primeiro
RUN ./gradlew --version

# Build DIRETO - clean + assembleRelease
RUN ./gradlew clean && \
    ./gradlew assembleRelease \
        --no-daemon \
        --stacktrace \
        --info

#########################################
# 3) Imagem final #
#########################################
FROM amazoncorretto:21-alpine

WORKDIR /app

RUN mkdir -p /app/apk

COPY --from=backend-build /getmoneyBackend/target/*.jar app.jar
COPY --from=mobile-build /getmoneyFrontend/android/app/build/outputs/apk/release/app-release.apk /app/apk/

EXPOSE 8401

CMD ["java", "-jar", "/app/app.jar"]