pipeline {
    agent any
    stages {
        stage('Verificar Repositório') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], useRemoteConfigs: [[url: 'https://github.com/Gustasilvadev/getmoney-ControleFinanceiro']]])
            }
        }

        stage('Instalar Dependências') {
            steps {
                script {
                    // Atualiza o PATH se necessário
                    env.PATH = "${env.MAVEN_HOME}\\bin;%PATH%"

                    dir('getmoneyBackend') {
                        // Instalar as dependências Maven antes de compilar o projeto
                        bat 'mvn clean install'
                    }
                }
            }
        }

        stage('Construir Imagem Docker') {
            steps {
                script {
                    // Atualiza o PATH para Docker e Maven
                    env.PATH = "${env.DOCKER_HOME};${env.MAVEN_HOME}\\bin;${env.PATH}"

                    def appName = 'getmoney'
                    def imageTag = "${appName}:${env.BUILD_ID}"

                    dir('getmoneyBackend') {
                        bat "docker build -t ${imageTag} ."
                    }
                }
            }
        }

        stage('Fazer Deploy') {
            steps {
                script {
                    def appName = 'getmoney'
                    def imageTag = "${appName}:${env.BUILD_ID}"

                    // Para e remove container existente, se houver
                    bat "docker stop ${appName} || exit 0"
                    bat "docker rm -v ${appName} || exit 0"

                    // Executa o container (descomente quando quiser rodar)
                    // bat "docker run -d --name ${appName} -p 8080:8080 ${imageTag}"
                }
            }
        }
    }

    post {
        success {
            echo 'Deploy realizado com sucesso!'
        }
        failure {
            echo 'Houve um erro durante o deploy.'
        }
    }
}
