pipeline {
    agent any
    stages {
        stage('Verificar Repositório') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], useRemoteConfigs: [[url: 'https://github.com/Gustasilvadev/getmoney-ControleFinanceiro']]])
            }
        }

          stage('Construir APK React Native') {
              steps {
                  script {
                      bat 'npm install'
                      bat 'cd android && gradlew assembleRelease'
                       bat 'cd android && gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a'

                      bat 'if not exist "%WORKSPACE%\\apk" mkdir "%WORKSPACE%\\apk"'
                      bat 'copy "android\\app\\build\\outputs\\apk\\release\\app-release.apk" "%WORKSPACE%\\apk\\getmoney.apk"'
                  }
              }
          }

        stage('Instalar Dependências Backend') {
            steps {
                script {
                    env.PATH = "${env.MAVEN_HOME}\\bin;%PATH%"
                    dir('getmoneyBackend') {
                        bat 'mvn clean install -DskipTests'
                    }
                }
            }
        }

        stage('Construir Imagem Docker') {
            steps {
                script {
                    env.PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"

                    def appName = 'getmoney'
                    def imageTag = "${appName}:${env.BUILD_ID}"

                    dir('getmoneyBackend') {
                        bat 'copy "..\\apk\\getmoney.apk" "."'
                        bat "docker build -t ${imageTag} ."
                        bat 'del "getmoney.apk"'
                    }
                }
            }
        }

        stage('Fazer Deploy') {
                    steps {
                        script {
                            def appName = 'getmoney'
                            def imageTag = "${appName}:${env.BUILD_ID}"

                            bat "docker stop ${appName} || echo 0"
                            bat "docker rm -v ${appName} || echo 0"

                            // bat "docker run -d --name ${appName} -p 8401:8401 ${imageTag}"
                        }
                    }
                }
            }

            post {
                success {
                    echo 'Deploy realizado com sucesso!'
                    echo 'APK disponível em: http://localhost:8401/install'
                }
                failure {
                    echo 'Houve um erro durante o deploy.'
                }
            }